### ISSUE TITLE
Can you add Chinese language to the GUI?

### ISSUE THREAD

**Issue by wcxu21** [UweKeim/ZetaResourceEditor#44]
Zeta Resource Editor provides Japanese, Russian and German. Can you consider adding Chinese? I am from China and I can help you translate it.
：-）

**Comment by UweKeim** [comment]
Unfortunately, this is not manageable.

Some years ago, the UI was in English and German.

Due to the the used technology (WinForms) I have to manually layout each form for each language. This makes it overly complex.

Therefore I removed German language support and intentionally only support English as the only UI language.

Sorry for that.

**Comment by wcxu21** [comment]
thank you for your reply.

Hope you can find a suitable solution in the future.
